project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources:
    - "robots.txt"

lang: ja

website:
  title: "Quarto実習資料"
  page-footer: 
    right: "© 2015-2026 Jaehyun Song"
  sidebar: 
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "1/ イントロダクション"
        href: 01_intro.qmd
      - text: "2/ 実習環境の導入"
        href: 02_install.qmd
      - text: "3/ Markdown文法"
        href: 03_markdown.qmd
      - text: "4/ 文書の作成"
        href: 04_document.qmd
      - text: "5/ スライドの作成"
        href: 05_slide.qmd
      - text: "6/ 共有"
        href: 06_share.qmd
      - section: "その他の内容"
        contents:
          - text: "YAMLヘッダー"
            href: A1_yaml.qmd
          - text: "ショートコード"
            href: A2_shortcodes.qmd
          - text: "拡張機能"
            href: A3_extensions.qmd
          - text: "テンプレート"
            href: A4_slide-template.qmd
      - section: "資料"
        contents:
          - text: "Quarto公式"
            href: "https://quarto.org/"
            target: _blank
          - text: "私たちのR"
            href: https://www.jaysong.net/RBook
            target: _blank
          - text: "JDCat分析ツール"
            href: https://binder.cs.rcos.nii.ac.jp/v2/gh/JaehyunSong/quarto_binder/HEAD
            target: _blank
          - text: "Posit Cloud"
            href: https://posit.cloud/
            target: _blank
          - text: "mybinder.org"
            href: https://mybinder.org/v2/gh/JaehyunSong/quarto_binder/main?urlpath=rstudio
            target: _blank

format:
  html:
    theme: a11y
    grid:
      sidebar-width: 250px
    number-sections: true
    toc: false
    link-external-newwindow: true

freeze: auto