project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
  resources:
    - "robots.txt"

lang: ja

website:
  title: "Quarto実習資料"
  page-footer: 
    right: "© 2015-2026 Jaehyun Song"
  sidebar: 
    style: floating
    search: true
    collapse-level: 2
    contents:
      - text: "1/ イントロダクション"
        href: intro.qmd
      - text: "2/ 実習環境の導入"
        href: install.qmd
      - text: "3/ Markdown文法"
        href: markdown.qmd
      - text: "4/ 文書の作成"
        href: document.qmd
      - text: "5/ スライドの作成"
        href: slide.qmd
      - text: "6/ 共有"
        href: share.qmd
      - section: "その他の内容"
        contents:
          - text: "YAMLヘッダー"
            href: yaml.qmd
          - text: "ショートコード"
            href: shortcodes.qmd
          - text: "拡張機能"
            href: extensions.qmd
      - section: "資料"
        contents:
          - text: "Quarto公式"
            href: "https://quarto.org/"
            target: _blank
          - text: "私たちのR"
            href: https://www.jaysong.net/RBook
            target: _blank
          - text: "mybinder.org"
            href: "#" #https://mybinder.org/v2/gh/JaehyunSong/quarto_binder/HEAD
            target: _blank

format:
  html:
    theme: a11y
    grid:
      sidebar-width: 250px
    number-sections: true
    toc-depth: 3
    link-external-newwindow: true

freeze: auto